name: build

on: [push, pull_request, workflow_dispatch]

env:
  PYTHON_VERSION: "3.10"
  POETRY_VIRTUALENVS_IN_PROJECT: "1"
  CACHE_VERSION: "1"
  COVERAGE: "1"

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ runner.os }}-reqs-${{ env.CACHE_VERSION }}-${{ hashFiles('**/poetry.lock') }}
      - run: pip install --upgrade pip setuptools wheel
      - run: pip install poetry && poetry install
  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ runner.os }}-reqs-${{ env.CACHE_VERSION }}-${{ hashFiles('**/poetry.lock') }}
      - run: pip install poetry && poetry install
      - run: ./scripts/lint.sh
  typecheck:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ runner.os }}-reqs-${{ env.CACHE_VERSION }}-${{ hashFiles('**/poetry.lock') }}
      - uses: actions/cache@v2
        with:
          path: .mypy_cache
          key: ${{ runner.os }}-mypy-${{ hashFiles('**/poetry.lock') }}
      - run: pip install poetry && poetry install
      - run: ./scripts/typecheck.sh
  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ runner.os }}-reqs-${{ env.CACHE_VERSION }}-${{ hashFiles('**/poetry.lock') }}
      - run: pip install poetry && poetry install
      - run: ./scripts/test.sh
      - uses: codecov/codecov-action@v2
  publish:
    needs: [lint, typecheck, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - run: ./scripts/publish.sh
  acceptance:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ runner.os }}-reqs-${{ env.CACHE_VERSION }}-${{ hashFiles('**/poetry.lock') }}
      - run: pip install poetry && poetry install
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - run: ./scripts/acceptance.sh
